name: Update Feed
on:
  schedule:
    - cron: '0 * * * *'  # Runs hourly
  workflow_dispatch:     # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm install
      
      - name: Generate RSS
        run: |
          mkdir -p docs
          node merger.js
          ls -la docs/  # Debug: Verify file creation
      
       
      - name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_branch: main  # ← Deploy to main branch instead of gh-pages
    publish_dir: ./docs